version: "3"
services:
    rancher:
        image: rancher/rancher:v2.7.0
        container_name: rancher
        ports:
            # do not change port
            - "80:80/tcp"
            - "443:443/tcp"
        volumes:
            - "./rancher-data:/var/lib/rancher"
        environment:
            - CATTLE_BOOTSTRAP_PASSWORD=1234
        privileged: true
