version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.385
    container_name: jenkins
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    # restart: always
    ports:
      - "8081:8080"
      - "51000:51000"
